default:
  bridge_name: default_bridge
  # IP CAMERA Parameters
  rtsp_link:
    - rtsp://admin:Alphax123@192.168.15.52/Streaming/channels/101
    - rtsp://admin:Alphax123@192.168.15.52/Streaming/channels/101
    - rtsp://admin:Alphax123@192.168.15.51/Streaming/channels/101
    - rtsp://admin:Alphax123@192.168.15.51/Streaming/channels/101
  cam_number_max: 4
  # basic parameters about strain data
  strain_number: 24	# 8, 16 , 24, 32
  quarter_bridge_string: 0
  axle_number: 4
  strain_sampling_rate: 1024
  # Micro strain conversion factor
  voffset: 8388608	# 0x800000 : 24bit data mid range
  vrange: 838.8607	# 0xFFFFFF / 20,000 uV : 24 bit full range divide full scale voltag
  gauge_factor: 211	# quater bridge gaugae factor    
  # strain event detection parameter [ event_channel_1 , event_channel_2 , ... , event_channel_n ]
  event_number_max: 4	# channel of event number ( one event by strain threshold per channel) / represent event number for road lane in wight calculation
  strain_threshold_channel: 
  - 1
  - 9
  - 10
  - 18        # channel of strain use for event threshold detection
  # STRAIN_THRESHOLD_MICROVOLT: [400,400,400,400]  # first stage for event threshold detection //35 on calibrate use 25 rail is 150
  # EVENT_THRESHOLD_MICROVOLT: [550,550,550,550]   # second stage for event threshold detection //40 on calibrate use 30 rail is 200
  strain_threshold_microvolt: 
  - 400
  - 400
  - 400
  - 400  # first stage for event threshold detection //35 on calibrate use 25 rail is 150
  event_threshold_microvolt: 
  - 500
  - 500
  - 500
  - 500   # second stage for event threshold detection //40 on calibrate use 30 rail is 200
  # strain event block recording parameter
  event_block_time: 	1	# recording and detect every xx second
  event_block_buffer_max: 20	# circular block buffer for recording data
  # event cam image recording : CAM-1 = lane 1 ( To Klongton ) / CAM-2 = lane 2 ( To Pratunam )
  event_cam_start:  
  - 2
  - 2
  - 2
  - 2		# cam start time when event occurred for each road lane [0,1]
  event_cam_finish: 
  - -1
  - -1
  - -1
  - -1	# cam stop time when event occurred for each road lane [-3,-2]  
  video_link:
    - rtsp://admin:Alphax123@192.168.15.52:554/Streaming/tracks/203
    - rtsp://admin:Alphax123@192.168.15.52:554/Streaming/tracks/203
    - rtsp://admin:Alphax123@192.168.15.51:554/Streaming/tracks/203
    - rtsp://admin:Alphax123@192.168.15.51:554/Streaming/tracks/203
  # event cam image recording : CAM-1 = lane 1 ( To Klongton ) / CAM-2 = lane 2 ( To Pratunam )
  video_cam_start:
    - 5
    - 5
    - 5
    - 5		# cam start time when event occurred for each road lane ( 10 sec recoding )
  video_cam_stop:
    - 5
    - 5
    - 5
    - 5		# cam stop time when event occurred for each road lane ( 10 sec recording )
  strain_plot_ch_list:
    - 1
    - 19
    - 2
    - 20
    - 9
    - 3
    - 10
    - 4
    - 17
    - 11
    - 18
    - 12   # List of All-CH-Number
  strain_ch_num_to_sensor_name:
    1: "G1_WS01-1"
    2: "G2_WS02-2"
    3: "G3_WS09-3"
    4: "G4_WS10-4"
    5: "G5_SG17-5"
    6: "G6_SG18-6"
    7: "-"
    8: "-"
    9: "G3_WS03-9"
    10: "G4_WS04-10"
    11: "G5_WS11-11"
    12: "G6_WS12-12"
    13: "G1_SG13-13"
    14: "G2_SG14-14"
    15: "-"
    16: "-"
    17: "G5_WS05-17"
    18: "G6_WS06-18"
    19: "G1_WS07-19"
    20: "G2_WS08-20"
    21: "G3_SG15-21"
    22: "G4_SG16-22"
    23: "-"
    24: "-"

  strain_plot_lane_ch_map:
    1:
      - 1
      - 19
      - 2
      - 20
      - 9
      - 3
    2:
      - 3
      - 9
      - 20 
      - 2
      - 19 
      - 1
    3:
      - 10 
      - 4
      - 17 
      - 11 
      - 18 
      - 12    
    4:
      - 12 
      - 18 
      - 11 
      - 17 
      - 4
      - 10

BANGPHLAT:
  bridge_name: BANGPHLAT
  # IP CAMERA Parameters
  rtsp_link:
    - rtsp://admin:Alphax123@192.168.15.52/Streaming/channels/101
    - rtsp://admin:Alphax123@192.168.15.52/Streaming/channels/101
    - rtsp://admin:Alphax123@192.168.15.51/Streaming/channels/101
    - rtsp://admin:Alphax123@192.168.15.51/Streaming/channels/101
  cam_number_max: 4
  # basic parameters about strain data
  strain_number: 24	# 8, 16 , 24, 32
  quarter_bridge_string: 0
  axle_number: 4
  strain_sampling_rate: 1024
  # Micro strain conversion factor
  voffset: 8388608	# 0x800000 : 24bit data mid range
  vrange: 838.8607	# 0xFFFFFF / 20,000 uV : 24 bit full range divide full scale voltag
  gauge_factor: 211	# quater bridge gaugae factor    
  # strain event detection parameter [ event_channel_1 , event_channel_2 , ... , event_channel_n ]
  event_number_max: 4	# channel of event number ( one event by strain threshold per channel) / represent event number for road lane in wight calculation
  strain_threshold_channel: 
  - 1
  - 9
  - 10
  - 18        # channel of strain use for event threshold detection
  # STRAIN_THRESHOLD_MICROVOLT: [400,400,400,400]  # first stage for event threshold detection //35 on calibrate use 25 rail is 150
  # EVENT_THRESHOLD_MICROVOLT: [550,550,550,550]   # second stage for event threshold detection //40 on calibrate use 30 rail is 200
  strain_threshold_microvolt: 
  - 400
  - 400
  - 400
  - 400  # first stage for event threshold detection //35 on calibrate use 25 rail is 150
  event_threshold_microvolt: 
  - 500
  - 500
  - 500
  - 500   # second stage for event threshold detection //40 on calibrate use 30 rail is 200
  # strain event block recording parameter
  event_block_time: 	1	# recording and detect every xx second
  event_block_buffer_max: 20	# circular block buffer for recording data
  # event cam image recording : CAM-1 = lane 1 ( To Klongton ) / CAM-2 = lane 2 ( To Pratunam )
  event_cam_start:  
  - 2
  - 2
  - 2
  - 2		# cam start time when event occurred for each road lane [0,1]
  event_cam_finish: 
  - -1
  - -1
  - -1
  - -1	# cam stop time when event occurred for each road lane [-3,-2]  
  video_link:
    - rtsp://admin:Alphax123@192.168.15.52:554/Streaming/tracks/203
    - rtsp://admin:Alphax123@192.168.15.52:554/Streaming/tracks/203
    - rtsp://admin:Alphax123@192.168.15.51:554/Streaming/tracks/203
    - rtsp://admin:Alphax123@192.168.15.51:554/Streaming/tracks/203
  # event cam image recording : CAM-1 = lane 1 ( To Klongton ) / CAM-2 = lane 2 ( To Pratunam )
  video_cam_start:
    - 5
    - 5
    - 5
    - 5		# cam start time when event occurred for each road lane ( 10 sec recoding )
  video_cam_stop:
    - 5
    - 5
    - 5
    - 5		# cam stop time when event occurred for each road lane ( 10 sec recording )
  strain_plot_ch_list:
    - 1
    - 19
    - 2
    - 20
    - 9
    - 3
    - 10
    - 4
    - 17
    - 11
    - 18
    - 12   # List of All-CH-Number
  strain_ch_num_to_sensor_name:
    1: "G1_WS01-1"
    2: "G2_WS02-2"
    3: "G3_WS09-3"
    4: "G4_WS10-4"
    5: "G5_SG17-5"
    6: "G6_SG18-6"
    7: "-"
    8: "-"
    9: "G3_WS03-9"
    10: "G4_WS04-10"
    11: "G5_WS11-11"
    12: "G6_WS12-12"
    13: "G1_SG13-13"
    14: "G2_SG14-14"
    15: "-"
    16: "-"
    17: "G5_WS05-17"
    18: "G6_WS06-18"
    19: "G1_WS07-19"
    20: "G2_WS08-20"
    21: "G3_SG15-21"
    22: "G4_SG16-22"
    23: "-"
    24: "-"

  strain_plot_lane_ch_map:
    1:
      - 1
      - 19
      - 2
      - 20
      - 9
      - 3
    2:
      - 3
      - 9
      - 20 
      - 2
      - 19 
      - 1
    3:
      - 10 
      - 4
      - 17 
      - 11 
      - 18 
      - 12    
    4:
      - 12 
      - 18 
      - 11 
      - 17 
      - 4
      - 10
